# Generated by Django 5.1.4 on 2024-12-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_nik',
            field=models.CharField(
                blank=True,
                help_text='Введите ник телеграма',
                max_length=100,
                null=True,
                verbose_name='Телеграм',
            ),
        ),
    ]
