# Generated by Django 5.1.4 on 2024-12-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0003_answer_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtry',
            name='points_quantity',
            field=models.SmallIntegerField(default=0, help_text='Укажите количество набранных баллов', verbose_name='Количество набранных баллов'),
        ),
    ]
