# Generated by Django 5.1.4 on 2024-12-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Укажите раздел для подписки', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app_material.section', verbose_name='Раздел'),
        ),
    ]
